workflows:
  build_ios:
    name: Build iOS App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          flutter build ios
    artifacts:
      - build/ios/ipa/*.ipa
