workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER }}
        APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
    scripts:
      - name: Install dependencies (skip pub get and pod install)
        script: |
          set -e
          cd ios
          # No ejecutar flutter pub get ni pod install
          cd ..
      - name: Build iOS
        script: |
          set -e
          cd ios
          # Copia los archivos que has subido como variables de entorno
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > AuthKey.p8
          # Aquí podrías agregar más comandos si es necesario
          cd ..
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
