name: lookwareapp
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  aligned_tooltip: ^0.0.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.0.1
  cloud_firestore_platform_interface: ^6.2.7
  cloud_firestore_web: ^4.0.1
  cloud_functions: ^5.0.1
  cloud_functions_platform_interface: ^5.5.3
  cloud_functions_web: ^4.9.8
  collection: ^1.18.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  firebase_storage: ^12.0.1
  file_picker: ^8.0.5
  firebase_auth: ^5.1.0
  firebase_auth_platform_interface: ^7.4.0
  firebase_auth_web: ^5.12.2
  firebase_core: ^3.1.0
  firebase_core_platform_interface: ^5.1.0
  firebase_core_web: ^2.17.2
  fl_chart: ^0.68.0
  firebase_performance: ^0.10.0+1
  firebase_performance_platform_interface: ^0.1.4+37
  firebase_performance_web: ^0.1.6+9
  flutter_animate: ^4.1.1+1
  flutter_cache_manager: ^3.3.1
  flutter_localizations:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.20
  font_awesome_flutter: ^10.6.0
  from_css_color: ^2.0.0
  go_router: ^14.1.4
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  google_sign_in_android: ^6.1.24
  google_sign_in_ios: ^5.6.4
  google_sign_in_platform_interface: ^2.4.2
  google_sign_in_web: ^0.12.1
  http: ^1.2.0
  image_picker: ^1.0.4
  image_picker_android: ^0.8.12+3
  image_picker_for_web: ^3.0.1
  image_picker_ios: ^0.8.8+2
  image_picker_platform_interface: ^2.9.1
  intl: ^0.19.0
  json_path: ^0.7.2
  mapbox_search: ^4.2.2
  mime_type: ^1.0.0
  page_transition: ^2.1.0
  path_provider: ^2.1.3
  path_provider_android: ^2.2.5
  path_provider_foundation: ^2.2.2
  path_provider_platform_interface: ^2.0.6
  percent_indicator: ^4.2.2
  plugin_platform_interface: ^2.1.8
  pointer_interceptor: ^0.10.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.3
  shared_preferences_foundation: ^2.3.4
  shared_preferences_platform_interface: ^2.3.1
  shared_preferences_web: ^2.2.1
  sign_in_with_apple: ^6.1.1
  sign_in_with_apple_platform_interface: ^1.0.0
  sign_in_with_apple_web: ^2.1.0
  signature: ^5.4.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.2.6
  stop_watch_timer: ^3.0.2
  stream_transform: ^2.1.0
  table_calendar: ^3.0.9
  timeago: ^3.2.2
  url_launcher: ^6.3.0
  url_launcher_android: ^6.3.3
  url_launcher_ios: ^6.2.5
  url_launcher_platform_interface: ^2.3.2
  uuid: ^4.4.0
  video_player: ^2.8.7
  video_player_android: ^2.5.0
  video_player_avfoundation: ^2.5.1
  video_player_platform_interface: ^6.2.1
  video_player_web: ^2.1.2
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.4
  webview_flutter_platform_interface: ^2.10.0
  webview_flutter_wkwebview: ^3.12.0
  webviewx_plus: ^0.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
